CREATE TABLE AddressData (
    City VARCHAR(255) CHARACTER SET utf8 ,
    Province CHAR(2),
	PRIMARY KEY(Province, City)
);
INSERT INTO AddressData (City, Province) VALUES
    ('﻿Toronto','ON'),
    ('Montréal','QC'),
    ('Vancouver','BC'),
    ('Ottawa','ON'),
    ('Calgary','AB'),
    ('Edmonton','AB'),
    ('Hamilton','ON'),
    ('Winnipeg','MB'),
    ('Québec','QC'),
    ('Oshawa','ON'),
    ('Kitchener','ON'),
    ('Halifax','NS'),
    ('London','ON'),
    ('Windsor','ON'),
    ('Victoria','BC'),
    ('Saskatoon','SK'),
    ('Barrie','ON'),
    ('Regina','SK'),
    ('Sudbury','ON'),
    ('Abbotsford','BC'),
    ('Sarnia','ON'),
    ('Sherbrooke','QC'),
    ('Saint John’s','NL'),
    ('Kelowna','BC'),
    ('Trois-Rivières','QC'),
    ('Kingston','ON'),
    ('Thunder Bay','ON'),
    ('Moncton','NB'),
    ('Saint John','NB'),
    ('Nanaimo','BC'),
    ('Peterborough','ON'),
    ('Saint-Jérôme','QC'),
    ('Red Deer','AB'),
    ('Lethbridge','AB'),
    ('Kamloops','BC'),
    ('Prince George','BC'),
    ('Medicine Hat','AB'),
    ('Drummondville','QC'),
    ('Chicoutimi','QC'),
    ('Fredericton','NB'),
    ('Chilliwack','BC'),
    ('North Bay','ON'),
    ('Shawinigan-Sud','QC'),
    ('Cornwall','ON'),
    ('Joliette','QC'),
    ('Belleville','ON'),
    ('Charlottetown','PE'),
    ('Victoriaville','QC'),
    ('Grande Prairie','AB'),
    ('Penticton','BC'),
    ('Sydney','NS'),
    ('Orillia','ON'),
    ('Rimouski','QC'),
    ('Timmins','ON'),
    ('Prince Albert','SK'),
    ('Campbell River','BC'),
    ('Courtenay','BC'),
    ('Orangeville','ON'),
    ('Moose Jaw','SK'),
    ('Brandon','MB'),
    ('Brockville','ON'),
    ('Saint-Georges','QC'),
    ('Sept-Îles','QC'),
    ('Rouyn-Noranda','QC'),
    ('Whitehorse','YT'),
    ('Owen Sound','ON'),
    ('Fort McMurray','AB'),
    ('Corner Brook','NL'),
    ('Val-d’Or','QC'),
    ('New Glasgow','NS'),
    ('Terrace','BC'),
    ('North Battleford','SK'),
    ('Yellowknife','NT'),
    ('Fort Saint John','BC'),
    ('Cranbrook','BC'),
    ('Edmundston','NB'),
    ('Rivière-du-Loup','QC'),
    ('Camrose','AB'),
    ('Pembroke','ON'),
    ('Yorkton','SK'),
    ('Swift Current','SK'),
    ('Prince Rupert','BC'),
    ('Williams Lake','BC'),
    ('Brooks','AB'),
    ('Quesnel','BC'),
    ('Thompson','MB'),
    ('Dolbeau','QC'),
    ('Powell River','BC'),
    ('Wetaskiwin','AB'),
    ('Nelson','BC'),
    ('Mont-Laurier','QC'),
    ('Kenora','ON'),
    ('Dawson Creek','BC'),
    ('Amos','QC'),
    ('Baie-Comeau','QC'),
    ('Hinton','AB'),
    ('Selkirk','MB'),
    ('Steinbach','MB'),
    ('Weyburn','SK'),
    ('Amherst','NS'),
    ('Kapuskasing','ON'),
    ('Dauphin','MB'),
    ('Dryden','ON'),
    ('Revelstoke','BC'),
    ('Happy Valley','NL'),
    ('Banff','AB'),
    ('Yarmouth','NS'),
    ('La Sarre','QC'),
    ('Parry Sound','ON'),
    ('Stephenville','NL'),
    ('Antigonish','NS'),
    ('Flin Flon','MB'),
    ('Fort Nelson','BC'),
    ('Smithers','BC'),
    ('Iqaluit','NU'),
    ('Bathurst','NB'),
    ('The Pas','MB'),
    ('Norway House','MB'),
    ('Meadow Lake','SK'),
    ('Vegreville','AB'),
    ('Stettler','AB'),
    ('Peace River','AB'),
    ('New Liskeard','ON'),
    ('Hearst','ON'),
    ('Creston','BC'),
    ('Marathon','ON'),
    ('Cochrane','ON'),
    ('Kindersley','SK'),
    ('Liverpool','NS'),
    ('Melville','SK'),
    ('Channel-Port aux Basques','NL'),
    ('Deer Lake','NL'),
    ('Saint-Augustin','QC'),
    ('Digby','NS'),
    ('Jasper','AB'),
    ('Hay River','NT'),
    ('Windsor','NS'),
    ('La Ronge','SK'),
    ('Deer Lake','ON'),
    ('Gaspé','QC'),
    ('Atikokan','ON'),
    ('Gander','NL'),
    ('Fort Chipewyan','AB'),
    ('Shelburne','NS'),
    ('Inuvik','NT'),
    ('Lac La Biche','AB'),
    ('Lillooet','BC'),
    ('Chapleau','ON'),
    ('Burns Lake','BC'),
    ('Gimli','MB'),
    ('Athabasca','AB'),
    ('Nelson House','MB'),
    ('Rankin Inlet','NU'),
    ('Port Hardy','BC'),
    ('Biggar','SK'),
    ('Wiarton','ON'),
    ('Wawa','ON'),
    ('Hudson Bay','SK'),
    ('Matagami','QC'),
    ('Arviat','NU'),
    ('Attawapiskat','ON'),
    ('Red Lake','ON'),
    ('Moosonee','ON'),
    ('Tofino','BC'),
    ('Igloolik','NU'),
    ('Inukjuak','QC'),
    ('Little Current','ON'),
    ('Baker Lake','NU'),
    ('Pond Inlet','NU'),
    ('Cap-Chat','QC'),
    ('Cambridge Bay','NU'),
    ('Thessalon','ON'),
    ('New Bella Bella','BC'),
    ('Cobalt','ON'),
    ('Cape Dorset','NU'),
    ('Pangnirtung','NU'),
    ('West Dawson','YT'),
    ('Kugluktuk','NU'),
    ('Geraldton','ON'),
    ('Gillam','MB'),
    ('Kuujjuaq','QC'),
    ('Lake Louise','AB'),
    ('Nipigon','ON'),
    ('Nain','NL'),
    ('Gjoa Haven','NU'),
    ('Fort McPherson','NT'),
    ('Argentia','NL'),
    ('Norman Wells','NT'),
    ('Churchill','MB'),
    ('Repulse Bay','NU'),
    ('Tuktoyaktuk','NT'),
    ('Berens River','MB'),
    ('Shamattawa','MB'),
    ('Baddeck','NS'),
    ('Coral Harbour','NU'),
    ('La Scie','NL'),
    ('Watson Lake','YT'),
    ('Taloyoak','NU'),
    ('Natashquan','QC'),
    ('Buchans','NL'),
    ('Hall Beach','NU'),
    ('Arctic Bay','NU'),
    ('Fort Good Hope','NT'),
    ('Mingan','QC'),
    ('Kangirsuk','QC'),
    ('Sandspit','BC'),
    ('Délįne','NT'),
    ('Fort Smith','NT'),
    ('Cartwright','NL'),
    ('Holman','NT'),
    ('Lynn Lake','MB'),
    ('Schefferville','QC'),
    ('Trout River','NL'),
    ('Forteau Bay','NL'),
    ('Fort Resolution','NT'),
    ('Hopedale','NL'),
    ('Pukatawagan','MB'),
    ('Trepassey','NL'),
    ('Kimmirut','NU'),
    ('Chesterfield Inlet','NU'),
    ('Eastmain','QC'),
    ('Dease Lake','BC'),
    ('Paulatuk','NT'),
    ('Fort Simpson','NT'),
    ('Brochet','MB'),
    ('Cat Lake','ON'),
    ('Radisson','QC'),
    ('Port-Menier','QC'),
    ('Resolute','NU'),
    ('Saint Anthony','NL'),
    ('Port Hope Simpson','NL'),
    ('Oxford House','MB'),
    ('Tsiigehtchic','NT'),
    ('Ivujivik','QC'),
    ('Stony Rapids','SK'),
    ('Alert','NU'),
    ('Fort Severn','ON'),
    ('Rigolet','NL'),
    ('Lansdowne House','ON'),
    ('Salluit','QC'),
    ('Łutselk’e','NT'),
    ('Uranium City','SK'),
    ('Burwash Landing','YT'),
    ('Grise Fiord','NU'),
    ('Big Beaverhouse','ON'),
    ('Island Lake','MB'),
    ('Ennadai','NU');
